sudo: false
language: python
matrix:
  include:
    # CPython 2.7
    - python: 2.7
      env: TOXENV=py27-integ
      stage: Client Tests
    - python: 2.7
      env: TOXENV=py27-examples
      stage: Client Tests
    # CPython 3.5
    - python: 3.5
      env: TOXENV=py35-integ
      stage: Client Tests
    - python: 3.5
      env: TOXENV=py35-examples
      stage: Client Tests
    # CPython 3.6
    - python: 3.6
      env: TOXENV=py36-integ
      stage: Client Tests
    - python: 3.6
      env: TOXENV=py36-examples
      stage: Client Tests
    # CPython 3.7
    # xenial + sudo are currently needed to get 3.7
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      env: TOXENV=py37-integ
      dist: xenial
      sudo: true
      stage: Client Tests
    - python: 3.7
      env: TOXENV=py37-examples
      dist: xenial
      sudo: true
      stage: Client Tests
    # CPython 3.8
    # xenial + sudo are currently needed to get 3.8
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.8
      env: TOXENV=py38-integ
      dist: xenial
      sudo: true
      stage: Client Tests
    - python: 3.8
      env: TOXENV=py38-examples
      dist: xenial
      sudo: true
      stage: Client Tests
    - python: 3.8
      env: TOXENV=py38-benchmark-kms
      dist: xenial
      sudo: true
      stage: Client Tests
    ########################
    # Test Vector Handlers #
    ########################
    # CPython 2.7
    - python: 2.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_1.3.3
      stage: Test Vector Handler Tests
    - python: 2.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_1.3.max
      stage: Test Vector Handler Tests
    - python: 2.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_latest
      stage: Test Vector Handler Tests
    # CPython 3.5
    - python: 3.5
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_1.3.3
      stage: Test Vector Handler Tests
    - python: 3.5
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_1.3.max
      stage: Test Vector Handler Tests
    - python: 3.5
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_latest
      stage: Test Vector Handler Tests
    # CPython 3.6
    - python: 3.6
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_1.3.3
      stage: Test Vector Handler Tests
    - python: 3.6
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_1.3.max
      stage: Test Vector Handler Tests
    - python: 3.6
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_latest
      stage: Test Vector Handler Tests
    # CPython 3.7
    - python: 3.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_1.3.3
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
    - python: 3.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_1.3.max
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
    - python: 3.7
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_latest
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
    # CPython 3.8
    - python: 3.8
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py38-awses_1.3.3
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
    - python: 3.8
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py38-awses_1.3.max
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
    - python: 3.8
      env: TEST_VECTOR_HANDLERS=1
        TOXENV=py38-awses_latest
      dist: xenial
      sudo: true
      stage: Test Vector Handler Tests
install: pip install tox
script:
  - |
    if [[ -n $TEST_VECTOR_HANDLERS ]];
      then cd test_vector_handlers;
      else if [[ -n $DECRYPT_ORACLE ]];
        then cd decrypt_oracle;
      fi;
    fi
  - tox
