sudo: false
language: python
matrix:
  include:
    # CPython 2.7
    - python: 2.7
      env: TOXENV=py27-local
    - python: 2.7
      env: TOXENV=py27-integ
    - python: 2.7
      env: TOXENV=py27-accept
    - python: 2.7
      env: TOXENV=py27-examples
    # CPython 3.4
    - python: 3.4
      env: TOXENV=py34-local
    - python: 3.4
      env: TOXENV=py34-integ
    - python: 3.4
      env: TOXENV=py34-accept
    - python: 3.4
      env: TOXENV=py34-examples
    # CPython 3.5
    - python: 3.5
      env: TOXENV=py35-local
    - python: 3.5
      env: TOXENV=py35-integ
    - python: 3.5
      env: TOXENV=py35-accept
    - python: 3.5
      env: TOXENV=py35-examples
    # CPython 3.6
    - python: 3.6
      env: TOXENV=py36-local
    - python: 3.6
      env: TOXENV=py36-integ
    - python: 3.6
      env: TOXENV=py36-accept
    - python: 3.6
      env: TOXENV=py36-examples
    # CPython 3.7
    # xenial + sudo are currently needed to get 3.7
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      env: TOXENV=py37-local
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-integ
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-accept
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-examples
      dist: xenial
      sudo: true
    # Upstream tests
    - python: 3.6
      env: TOXENV=nocmk
    - python: 2.7
      env: TOXENV=test-upstream-requirements-py27
    # xenial + sudo are currently needed to get 3.7
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      env: TOXENV=test-upstream-requirements-py37
      dist: xenial
      sudo: true
    # Security
    - python: 3.6
      env: TOXENV=bandit
    # Linting and autoformatting
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
    - python: 3.6
      env: TOXENV=flake8-examples
    - python: 3.6
      env: TOXENV=pylint-examples
    - python: 3.6
      env: TOXENV=black-check
    - python: 3.6
      env: TOXENV=isort-check
    ########################
    # Test Vector Handlers #
    ########################
    # CPython 2.7
    - python: 2.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_1.3.0
    - python: 2.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_1.3.max
    - python: 2.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py27-awses_latest
    # CPython 3.4
    - python: 3.4
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py34-awses_1.3.0
    - python: 3.4
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py34-awses_1.3.max
    - python: 3.4
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py34-awses_latest
    # CPython 3.5
    - python: 3.5
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_1.3.0
    - python: 3.5
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_1.3.max
    - python: 3.5
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py35-awses_latest
    # CPython 3.6
    - python: 3.6
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_1.3.0
    - python: 3.6
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_1.3.max
    - python: 3.6
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py36-awses_latest
    # CPython 3.7
    - python: 3.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_1.3.0
      dist: xenial
      sudo: true
    - python: 3.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_1.3.max
      dist: xenial
      sudo: true
    - python: 3.7
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=py37-awses_latest
      dist: xenial
      sudo: true
    # Linters
    - python: 3.6
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=bandit
    - python: 3.6
      env:
        TEST_VECTOR_HANDLERS=1
        TOXENV=readme
    # Pending buildout of docs
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=docs
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=doc8
    # Pending linting cleanup
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=flake8
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=pylint
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=flake8-tests
    #- python: 3.6
    #  env:
    #    TEST_VECTOR_HANDLERS=1
    #    TOXENV=pylint-tests
    ##################
    # Decrypt Oracle #
    ##################
    # CPython 2.7
    - python: 2.7
      env:
        DECRYPT_ORACLE=1
        TOXENV=py27-local
    # CPython 3.4
    - python: 3.4
      env:
        DECRYPT_ORACLE=1
        TOXENV=py34-local
    # CPython 3.5
    - python: 3.5
      env:
        DECRYPT_ORACLE=1
        TOXENV=py35-local
    # CPython 3.6
    - python: 3.6
      env:
        DECRYPT_ORACLE=1
        TOXENV=py36-local
    # CPython 3.7
    - python: 3.7
      env:
        DECRYPT_ORACLE=1
        TOXENV=py37-local
      dist: xenial
      sudo: true
    # Linters
    - python: 3.6
      env:
        DECRYPT_ORACLE=1
        TOXENV=bandit
    - python: 3.6
      env:
        DECRYPT_ORACLE=1
        TOXENV=readme
    # Pending buildout of docs
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=docs
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=doc8
    # Pending linting cleanup
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=flake8
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=pylint
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=flake8-tests
    #- python: 3.6
    #  env:
    #    DECRYPT_ORACLE=1
    #    TOXENV=pylint-tests
install: pip install tox
script:
  - if [[ -n $TEST_VECTOR_HANDLERS ]]; then cd test_vector_handlers; else if [[ -n $DECRYPT_ORACLE ]]; then cd decrypt_oracle; fi
  - tox
