sudo: false
language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-local
    - python: 2.7
      env: TOXENV=py27-integ
    - python: 2.7
      env: TOXENV=py27-accept
    - python: 2.7
      env: TOXENV=py27-examples
    - python: 3.4
      env: TOXENV=py34-local
    - python: 3.4
      env: TOXENV=py34-integ
    - python: 3.4
      env: TOXENV=py34-accept
    - python: 3.4
      env: TOXENV=py34-examples
    - python: 3.5
      env: TOXENV=py35-local
    - python: 3.5
      env: TOXENV=py35-integ
    - python: 3.5
      env: TOXENV=py35-accept
    - python: 3.5
      env: TOXENV=py35-examples
    - python: 3.6
      env: TOXENV=py36-local
    - python: 3.6
      env: TOXENV=py36-integ
    - python: 3.6
      env: TOXENV=py36-accept
    - python: 3.6
      env: TOXENV=py36-examples
    - python: 3.7
      env: TOXENV=py37-local
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-integ
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-accept
      dist: xenial
      sudo: true
    - python: 3.7
      env: TOXENV=py37-examples
      dist: xenial
      sudo: true
    - python: 3.6
      env: TOXENV=nocmk
    - python: 3.6
      env: TOXENV=bandit
    - python: 3.6
      env: TOXENV=doc8
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=readme
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=pylint
    - python: 3.6
      env: TOXENV=flake8-tests
    - python: 3.6
      env: TOXENV=pylint-tests
    - python: 3.6
      env: TOXENV=flake8-examples
    - python: 3.6
      env: TOXENV=pylint-examples
    - python: 3.6
      env: TOXENV=black-check
    - python: 3.6
      env: TOXENV=isort-check
install: pip install tox
script: tox
